name: Starriv.com CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-npm-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn
    - name: Build Application
      run: yarn build
  build-and-push-image:
    runs-on: ubuntu-latest
    needs: run-npm-build
    permissions: 
      contents: read
      packages: write 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/image:latest
  deploy-image:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: auto deploy docker image
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /root/starriv.com
            # sed "s/image:\w\+/image:${{github.sha}}/" docker-compose.yml
            docker-compose pull
            docker-compose stop
            docker-compose rm -f
            docker-compose up -d
          host: ${{ secrets.QCLOUD_HOST }}
          user: root
          key: ${{ secrets.QCLOUD_PRIVATE_KEY}}
